apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: "{{ .Values.deployment.port }}"
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
  