apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ .Release.Name }}-deploy
   labels:
      app: {{ .Release.Name }}
      env: {{ .Values.owner }}
      owner: DmitryAvdonin
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
         project: {{ .Values.project }}
   template:
      metadata:
         labels:
            project: {{ .Values.project }}
      spec:
         containers:
            - name: {{ .Release.Name }}
              image: {{ .Values.container.image }} 
              envFrom:
                 - secretRef:
                      name: postgres-secret
              ports:
                 - containerPort: {{ .Values.container.port }}

