apiVersion: apps/v1
kind: Deployment                                # Type of the kubernetes resource
metadata:
  name: {{ .Release.Name }}                       # Name of the deployment
  labels:                                        # Labels applied to this deployment 
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:                                  # This deployment applies to the Pods matching the specified labels
      app: {{ .Release.Name }}
      tier: postgres
  replicas: {{ .Values.replicaCount }}
  template:                                       # Template for the Pods in this deployment
    metadata:
      labels:                                     # Labels to be applied to the Pods in this deployment
        app: {{ .Release.Name }}
        tier: postgres
    spec:                                         # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: {{ .Values.container.image }}                   # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:                                # Get the environmental variables from a secret file whose name is "secret" 
            - secretRef:
                name: postgres-secret
            
          ports:
            - containerPort: {{ .Values.container.dbPort }}                   # The port that the container exposes 
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage     # This name should match the name specified in `volumes.name`
      volumes:                                      # A PersistentVolume is mounted as a volume to the Pod 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim