apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
         - name: migration
           image: dmitryavdonin/migrate:latest
           envFrom:
              - secretRef:
                   name: postgres-secret
           command: ["/usr/bin/migrate"]       
      restartPolicy: Never
  backoffLimit: 4
